# Generated by Django 6.0.7 on 2026-07-25 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_passwordreset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordReset",
        ),
    ]
