# Generated by Django 6.0.7 on 2026-07-27 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupmember",
            name="unique_user_per_group",
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("user", "group")},
        ),
    ]
