# Generated by Django 6.0.7 on 2026-07-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0002_remove_groupmember_unique_user_per_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="Misc", max_length=20)),
                (
                    "split_type",
                    models.CharField(
                        choices=[
                            ("EQUAL", "Equal"),
                            ("EXACT", "Exact"),
                            ("PERCENT", "Percent"),
                        ],
                        default="EQUAL",
                        max_length=20,
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpensePerMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "share_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perexpense",
                        to="expense.expense",
                    ),
                ),
                (
                    "group_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.groupmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status", models.BooleanField(default=False)),
                ("first_payment", models.DateTimeField(auto_now_add=True)),
                ("latest_payment", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="expense.expense",
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_sent",
                        to="group.groupmember",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_received",
                        to="group.groupmember",
                    ),
                ),
            ],
        ),
    ]
