# Generated by Django 6.0.7 on 2026-07-28 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="percent",
        ),
    ]
