# Generated by Django 6.0.7 on 2026-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_remove_expense_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensepermember",
            name="percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
