# Generated by Django 6.0.7 on 2026-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0003_expensepermember_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensepermember",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="expensepermember",
            name="share_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
