# Generated by Django 6.0.7 on 2026-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0004_alter_expensepermember_paid_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensepermember",
            name="percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
