# Generated by Django 6.0.7 on 2026-07-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0006_alter_expense_group"),
        ("group", "0002_remove_groupmember_unique_user_per_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense",
                to="group.group",
            ),
        ),
    ]
