# Generated by Django 6.0.7 on 2026-08-01 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_remove_groupmember_unique_user_per_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(' GROUP CREATE', 'Group Creation'), ('MEMBER ADD', 'Member Add'), ('MEMBER REMOVE', 'Member remove'), ('EXPENSE CREATE', 'Expense Create'), ('EXPENSE UPDATE', 'Expense Update'), ('EXPENSE DELETE', 'Expense Delete'), ('PAYMENT ADD', 'Payment Add'), ('SETTLEMENT_CREATE', 'Settlement Create'), ('GROUP DELETE', 'Group delete')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activities', to='group.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
