# Generated by Django 6.0.7 on 2026-08-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options_remove_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[(' GROUP CREATE', 'Group Creation'), ('MEMBER ADD', 'Member Add'), ('MEMBER REMOVE', 'Member remove'), ('EXPENSE CREATE', 'Expense Create'), ('EXPENSE UPDATE', 'Expense Update'), ('EXPENSE DELETE', 'Expense Delete'), ('PAYMENT', 'Payment'), ('SETTLEMENT CREATE', 'Settlement Create')], max_length=50),
        ),
    ]
