# Generated by Django 6.0.7 on 2026-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[(' GROUP CREATE', 'Group Creation'), ('MEMBER ADD', 'Member Add'), ('MEMBER REMOVE', 'Member remove'), ('EXPENSE CREATE', 'Expense Create'), ('EXPENSE UPDATE', 'Expense Update'), ('EXPENSE DELETE', 'Expense Delete'), ('PAYMENT', 'Payment'), ('SETTLEMENT CREATE', 'Settlement Create'), ('GROUP DELETE', 'Group deleted')], max_length=50),
        ),
    ]
