# Generated by Django 6.0.7 on 2026-08-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_type'),
        ('group', '0002_remove_groupmember_unique_user_per_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to='group.group'),
        ),
    ]
